### ISSUE TITLE
Improvement Suggestion

### ISSUE THREAD

**Issue by battamo** [corcoran/Hangar#19]
Hello, 

At the moment the widget will only show a limited number of apps.

It would be great if this limit could be removed or at least increased.

The nexus 6 would easily show 100 apps on a screen without being cramped.

If many more apps could be dispaleyed using the sorting algortihm that would be very usefull.

Otherwise excellent app!

Thanks,
Jesper

**Comment by dAnjou** [comment]
You should change the issue title to something more meaningful like "Remove limitation of number of apps shown in widget".

But yeah, would be great to see this fixed/improved. Right now the limit seems to be 35.

![screenshot_20170119-155230](https://cloud.githubusercontent.com/assets/117147/22111616/33b63b54-de60-11e6-9373-ff74702f5d61.png)

**Comment by zentiggr** [comment]
PR submitted to raise the limit to 60 (I can use 48 medium size icons on my screen, not sure about small size).

**Comment by bfday** [comment]
hey, guys, when do u approve/increase limit?

**Comment by onmyouji** [comment]
I think this project has already been neglected, I hope someone can takeover and fork it.

**Comment by corcoran** [comment]
Coincidentally this project is being redone.  Stay tuned for an update in the next week!

**Comment by corcoran** [comment]
https://github.com/mimicmobile/hangar/
