### ISSUE TITLE
Pinned apps don't pass over to second page + also get ignored from list

### ISSUE THREAD

**Issue by salgadobreno** [corcoran/Hangar#37]
I had single notification row with 10 apps and 11 pinned apps, the 11th being YouTube and 2 pages of apps.

Expected behavior would be that going into the second page, the first app on the second page would be YouTube but not only it's not, the pinned app is then also ignored from the "default list". I.e.: YouTube as the 11th pinned won't appear on second page, but with it as "unpinned" it "makes the list".

I've also reproduced this with having 2 rows enabled & pinning 21 apps.

I'll try providing a PR for this, would be nice having some feedback on if you're still coming around here sometimes too tho :)

**Comment by corcoran** [comment]
This has been fixed in the re-write! https://github.com/mimicmobile/hangar/

**Comment by salgadobreno** [comment]
I'll deffo check it out :)
